name: qration
description: "A scanner and QR code creator."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.2
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  ming_cute_icons: ^0.0.7
  line_awesome_flutter: ^3.0.1
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  logger: ^2.5.0
  shared_preferences: ^2.3.4
  provider: ^6.1.2
  intl: ^0.19.0
  intl_utils: ^2.8.7
  flutter_localizations:
    sdk: flutter
  mobile_scanner: ^7.0.0-beta.4
  qr_flutter: ^4.1.0
  screenshot: ^3.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  image_gallery_saver_plus: ^3.0.5
  share_plus: ^10.1.1
  url_launcher: ^6.3.1
  country_code_picker: ^3.1.0
  flutter_contacts: ^1.1.9+2
  add_2_calendar: ^3.0.1
  wifi_iot: ^0.3.19+1
  free_map: ^2.0.2
  flutter_colorpicker: ^1.1.0
  audioplayers: ^6.1.0
  vibration: ^3.1.3
  smooth_page_indicator: ^1.2.0+3
  pdf: ^3.11.1
  excel: ^4.0.6
  csv: ^6.0.0
  device_info_plus: ^11.2.0
  file_picker: ^9.0.2
  webview_flutter: ^4.8.0
  toastification: ^2.3.0
  dependency_validator: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/sounds/
    - assets/fonts/

  fonts:
    - family: QrationIcons
      fonts:
        - asset: assets/fonts/QrationIcons.ttf
        - asset: assets/fonts/Montserrat.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo_icon.png"
